name: Build safe-contracts Docker Image
on:
  push:
    branches:
      - 'ci_v1.3.0'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: build and push safe-contracts
            image: safe-contracts
            dockerfile: Dockerfile
            context: .
            buildargs: ''
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Prepare Environment Variables
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" | tee -a $GITHUB_ENV
          GIT_BRANCH=$(git branch --show-current)
          echo "GIT_BRANCH=$GIT_BRANCH" | tee -a $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: ${{ matrix.name }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          push: true
          tags: |
            ${{ secrets.ECR_REGISTRY }}/${{ matrix.image }}:${{ env.GIT_BRANCH }}-${{ github.sha }}
            ${{ secrets.ECR_REGISTRY }}/${{ matrix.image }}:${{ env.GIT_BRANCH }}-${{ env.SHORT_SHA }}
          file: ${{ matrix.dockerfile }}
          provenance: false